services:
  bot:
    build:
      context: .
      dockerfile: etc/Dockerfile
    restart: always
    env_file: ./.env
    networks:
      - main_net
    volumes:
      - /home/bob/tg_bots/e-cigarette/image:/image
  db:
    image: postgres:15.3-alpine
    env_file: ./.env
    environment:
      TZ: "Asia/Almaty"
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - main_net

  redis:
    image: redis:7.2.5-alpine
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    volumes:
     - ./redisdata:/data
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
        echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    ports:
      - 6379:6379
    networks:
      - main_net

networks:
  main_net:
    external: True
volumes:
    postgres_data:
